[package]
name = "vec_int_stats"
version = "0.1.0"
authors = ["Wei-Zou <wz.weizou@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
